{% set name = "mashumaro" %}
{% set version = "2.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mashumaro-{{ version }}.tar.gz
  sha256: 343b6e2d3e432e31973688c4c8821dcd6ef41fd33264b992afc4aecbfd155f18

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    # While mashumaro supports 3.6, there is no conda-forge package for
    # backports-datetime-fromisoformat for python>3.8. Thus to support python 3.9
    # and higher, we would need to remove noarch. But conda-forge only builds >=3.7.
    # Thus removing noarch is pointless, and we increase the minimum version to 3.7
    # while keeping noarch, and omit the 3.6 dependencies.
    - python >=3.7
  run:
    # https://github.com/Fatal1ty/mashumaro/blob/v{{ version }}/setup.py
    - python >=3.7
    - typing-extensions
    - msgpack-python >=0.5.6
    - pyyaml >=3.13
    # # For Python 3.6 support:
    # - dataclasses
    # - backports-datetime-fromisoformat

test:
  imports:
    - mashumaro
    - mashumaro.meta
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Fatal1ty/mashumaro
  summary: Fast serialization framework on top of dataclasses
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
    - maresb
