{% set name = "mashumaro" %}
{% set version = "3.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mashumaro-{{ version }}.tar.gz
  sha256: 97b07e5f1cc61a7158d082c33ec1eb2d11d3f94b5d656cff9637d201aa2fe547

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    # https://github.com/Fatal1ty/mashumaro/blob/v{{ version }}/setup.py
    - python >=3.6
    - typing-extensions
    # For Python 3.6 support:
    - dataclasses
    - backports-datetime-fromisoformat

test:
  imports:
    - mashumaro
    - mashumaro.core
    - mashumaro.core.meta
    - mashumaro.dialects
    - mashumaro.mixins
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Fatal1ty/mashumaro
  summary: Fast serialization framework on top of dataclasses
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
    - maresb
