{% set name = "mashumaro" %}
{% set version = "2.10.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mashumaro-{{ version }}.tar.gz
  sha256: 1ae8239154801a24d6b58118b5a474b1a1bbaa5f2f751d551ed91295ad555881

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - backports-datetime-fromisoformat
    - dataclasses
    - msgpack-python >=0.5.6
    - python >=3.6
    - pyyaml >=3.13
    - typing-extensions

test:
  imports:
    - mashumaro
    - mashumaro.meta
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Fatal1ty/mashumaro
  summary: Fast serialization framework on top of dataclasses
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
    - maresb
