{% set name = "mashumaro" %}
{% set version = "2.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mashumaro-{{ version }}.tar.gz
    sha256: ec402ecbbcc6b5d9b12a1ebfa90af4954fcd7583b745bcf22da156f2a55d1355
  - url: https://raw.githubusercontent.com/Fatal1ty/mashumaro/v{{ version }}/LICENSE
    sha256: 6d1af7a48fd311beb8745fbdd517f8f64fb9d8cbbd8726cdd22dbee66fdf51c3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - backports-datetime-fromisoformat
    - dataclasses
    - msgpack-python >=0.5.6
    - python >=3.6
    - pyyaml >=3.13
    - typing-extensions

test:
  imports:
    - mashumaro
    - mashumaro.meta
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Fatal1ty/mashumaro
  summary: Fast serialization framework on top of dataclasses
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
    - maresb
