{% set name = "mashumaro" %}
{% set version = "3.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mashumaro-{{ version }}.tar.gz
  sha256: 663c6ba9360890e5b28df214008ae5be8330d239dca0f393862695e76bf11895

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    # While mashumaro supports 3.6, there is no conda-forge package for
    # backports-datetime-fromisoformat. Thus to support 3.6 we would need
    # to remove noarch. But conda-forge only builds <=3.7. Thus removing
    # noarch is pointless, and we increase the minimum version to 3.7 while
    # keeping noarch, and omit the 3.6 dependencies.
    - python >=3.7
  run:
    # https://github.com/Fatal1ty/mashumaro/blob/v{{ version }}/setup.py
    - python >=3.7
    - typing-extensions
    # # For Python 3.6 support:
    # - dataclasses
    # - backports-datetime-fromisoformat

test:
  imports:
    - mashumaro
    - mashumaro.core
    - mashumaro.core.meta
    - mashumaro.dialects
    - mashumaro.mixins
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Fatal1ty/mashumaro
  summary: Fast serialization framework on top of dataclasses
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
    - maresb
