{% set name = "mashumaro" %}
{% set version = "3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ceb3de53029219bbbb0385ca600b59348dcd14e0c68523986c6d51889ad338f5

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - typing-extensions >=4.1.0
    # Extra dependency is required by the dependant package dbt https://github.com/dbt-labs/dbt-core/blob/v1.5.3/core/setup.py#L57
    - msgpack-python >=0.5.6

test:
  imports:
    - mashumaro
    - mashumaro.core
    - mashumaro.mixins
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/Fatal1ty/mashumaro
  dev_url: https://github.com/Fatal1ty/mashumaro
  doc_url: https://github.com/Fatal1ty/mashumaro
  summary: Fast serialization framework on top of dataclasses
  description: |
    Fast and well tested serialization library on top of dataclasses
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
    - maresb
